# Copyright (C) 2024 Ivan Veloz.  All Rights Reserved.
#
# SPDX-License-Identifier: MIT
#
# SPDX-FileContributor: Ivan Veloz, 2024

SOURCEDIRS	:= arm9/source coreSNTP/source
INCLUDEDIRS	:= include coreSNTP/source/include

BLOCKSDS	?= /opt/blocksds/core
LIBS		:= -ldswifi9 -lnds9
LIBDIRS		:= $(BLOCKSDS)/libs/dswifi \
			   $(BLOCKSDS)/libs/libnds \
			   

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile.arm9
