# Copyright (C) 2024 Ivan Veloz.  All Rights Reserved.
#
# SPDX-License-Identifier: MIT
#
# SPDX-FileContributor: Ivan Veloz, 2024

SOURCEDIRS	:= arm7/source coreSNTP/source
INCLUDEDIRS	:= include arm7/include coreSNTP/source/include

BLOCKSDS	?= /opt/blocksds/core
LIBS		:= -lnds7 -ldswifi7 -lmm7 -lc
LIBDIRS		:= $(BLOCKSDS)/libs/libnds \
		   $(BLOCKSDS)/libs/dswifi \
		   $(BLOCKSDS)/libs/maxmod

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile.arm7
